version: "3.8"

services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  fx_db:
    image: postgres:14-alpine
    container_name: campuscross_fx_db
    environment:
      POSTGRES_DB: fx_alerts_db
      POSTGRES_USER: fx_user
      POSTGRES_PASSWORD: fx_password
    ports:
      - "5432:5432" # Standard PostgreSQL port
    volumes:
      - fx_data:/var/lib/postgresql/data # Persistent storage


volumes:
  redis-data:
  fx_data:
